# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 20:05
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='评论内容'),
        ),
    ]
